services:
  mastacos:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  mastacos_ui:
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=development
    # This is the key part for browser launch
    labels:
      - "com.microsoft.visualstudio.debuggee.program=http://localhost:8081"