name: MasTacos
services:
  mastacos:
    image: ${DOCKER_REGISTRY-}mastacos
    build:
      context: .
      dockerfile: MasTacos/Dockerfile
    container_name: WebAPI
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=mas_tacos;User=mas_tacos_user;Password=mas_tacos_password;
      - ASPNETCORE_URLS=http://0.0.0.0:80
    networks:
      - mastacos-network
      
  mastacos_ui:
    build:
      context: ./mastacos_ui/mastacos_ui
      dockerfile: Dockerfile
    container_name: VueApp
    volumes:
      - ./mastacos_ui/mastacos_ui:/app
      - /app/node_modules
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=development
    tty: true
    command: sh -c "npm install && npm run serve -- --host 0.0.0.0"
    networks:
      - mastacos-network
    depends_on:
      - mastacos
      
  db:
    image: mysql:8.0
    container_name: MySQL
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mas_tacos
      - MYSQL_USER=mas_tacos_user
      - MYSQL_PASSWORD=mas_tacos_password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./MasTacos/Scripts:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - mastacos-network

volumes:
  db-data:
  
networks:
  mastacos-network:
    driver: bridge