[phases.setup]
nixPkgs = ['dotnet-sdk_6']

[phases.build]
cmds = [
  'dotnet restore MasTacos/MasTacos.csproj',
  'dotnet build MasTacos/MasTacos.csproj -c Release',
  'dotnet publish MasTacos/MasTacos.csproj -c Release -o /app/publish'
]

[start]
cmd = 'dotnet /app/publish/MasTacos.dll'